/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnersAssetRouteImport } from './routes/partners-asset'
import { Route as PartnersReferralRouteImport } from './routes/partners-referral'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsDubaiRouteImport } from './routes/markets.dubai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersAssetRoute = PartnersAssetRouteImport.update({
  id: '/partners-asset',
  path: '/partners-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersReferralRoute = PartnersReferralRouteImport.update({
  id: '/partners-referral',
  path: '/partners-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsDubaiRoute = MarketsDubaiRouteImport.update({
  id: '/markets/dubai',
  path: '/markets/dubai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/partners-asset': typeof PartnersAssetRoute
  '/partners-referral': typeof PartnersReferralRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/markets/dubai': typeof MarketsDubaiRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/partners-asset': typeof PartnersAssetRoute
  '/partners-referral': typeof PartnersReferralRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/markets/dubai': typeof MarketsDubaiRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/partners-asset': typeof PartnersAssetRoute
  '/partners-referral': typeof PartnersReferralRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/markets/dubai': typeof MarketsDubaiRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/partners'
    | '/partners-asset'
    | '/partners-referral'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/who-we-are'
    | '/markets/dubai'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/partners'
    | '/partners-asset'
    | '/partners-referral'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/who-we-are'
    | '/markets/dubai'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/partners'
    | '/partners-asset'
    | '/partners-referral'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/who-we-are'
    | '/markets/dubai'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnersRoute: typeof PartnersRoute
  PartnersAssetRoute: typeof PartnersAssetRoute
  PartnersReferralRoute: typeof PartnersReferralRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  MarketsDubaiRoute: typeof MarketsDubaiRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners-asset': {
      id: '/partners-asset'
      path: '/partners-asset'
      fullPath: '/partners-asset'
      preLoaderRoute: typeof PartnersAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners-referral': {
      id: '/partners-referral'
      path: '/partners-referral'
      fullPath: '/partners-referral'
      preLoaderRoute: typeof PartnersReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/dubai': {
      id: '/markets/dubai'
      path: '/markets/dubai'
      fullPath: '/markets/dubai'
      preLoaderRoute: typeof MarketsDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnersRoute: PartnersRoute,
  PartnersAssetRoute: PartnersAssetRoute,
  PartnersReferralRoute: PartnersReferralRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  MarketsDubaiRoute: MarketsDubaiRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
